"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
var aa,ba,ca;aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;ca=function(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}};
ca("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ca("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});_.da=_.da||{};_.m=this;_.ea="closure_uid_"+(1E9*Math.random()>>>0);_.ha=Date.now||function(){return+new Date};

}catch(e){_._DumpException(e)}
try{
var qa,ra;_.n=function(a){return void 0!==a};_.p=function(a){return"string"==typeof a};_.ia=function(a){return"number"==typeof a};_.ja=function(a){a=a.split(".");for(var b=_.m,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};_.ka=function(){};
_.la=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ma=function(a){return"array"==_.la(a)};_.na=function(a){var b=_.la(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.oa=function(a){return"function"==_.la(a)};_.pa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};qa=function(a,b,c){return a.call.apply(a.bind,arguments)};
ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.q=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.q=qa:_.q=ra;return _.q.apply(null,arguments)};
_.sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.ta=function(a,b){a=a.split(".");var c=_.m;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.n(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}};
_.r=function(a,b){function c(){}c.prototype=b.prototype;a.A=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ic=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};
_.ua=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ua);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.r(_.ua,Error);_.ua.prototype.name="CustomError";var va;va=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.p(a))return _.p(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.wa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.p(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d};_.xa=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.p(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.ya=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Aa=function(a,b){b=_.za(a,b,void 0);return 0>b?null:_.p(a)?a.charAt(b):a[b]};_.za=function(a,b,c){for(var d=a.length,e=_.p(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Ba=function(a,b){return 0<=va(a,b)};_.Da=function(a,b){b=va(a,b);var c;(c=0<=b)&&_.Ca(a,b);return c}; _.Ca=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Ea=function(a){return Array.prototype.concat.apply([],arguments)};_.Fa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Ka;_.Ga=function(a,b){return 0==a.lastIndexOf(b,0)};_.Ha=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ia=function(a){return/^[\s\xa0]*$/.test(a)};_.Ja=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.La=function(a,b){var c=0;a=(0,_.Ja)(String(a)).split(".");b=(0,_.Ja)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=Ka(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||Ka(0==f[2].length,0==g[2].length)||Ka(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c}; Ka=function(a,b){return a<b?-1:a>b?1:0};
var Ma;Ma=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Na=function(a){return null==a?"":String(a)};a:{var Pa=_.m.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){_.Oa=Qa;break a}}_.Oa=""}_.v=function(a){return-1!=_.Oa.indexOf(a)};var Sa,Ua;_.Ra=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Sa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Ta=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Ua="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Va=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ua.length;f++)c=Ua[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Wa=function(){return _.v("Trident")||_.v("MSIE")};_.Xa=function(){return _.v("Firefox")||_.v("FxiOS")};_.Za=function(){return _.v("Safari")&&!(_.Ya()||_.v("Coast")||_.v("Opera")||_.v("Edge")||_.Xa()||_.v("Silk")||_.v("Android"))};_.Ya=function(){return(_.v("Chrome")||_.v("CriOS"))&&!_.v("Edge")};
var $a,ab;$a=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};ab=function(){return $a()||_.v("iPad")||_.v("iPod")};_.bb=function(){return _.v("Macintosh")};_.cb=function(){return _.v("Windows")};_.db=function(){return _.v("CrOS")};var eb=function(a){eb[" "](a);return a};eb[" "]=_.ka;_.fb=function(a,b){try{return eb(a[b]),!0}catch(c){}return!1};_.gb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var hb,kb,ob,rb,sb,wb,xb,zb;hb=_.v("Opera");_.jb=_.Wa();kb=_.v("Edge");_.lb=_.v("Gecko")&&!(-1!=_.Oa.toLowerCase().indexOf("webkit")&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.mb=-1!=_.Oa.toLowerCase().indexOf("webkit")&&!_.v("Edge");ob=_.m.navigator||null;_.nb=ob&&ob.platform||"";_.pb=_.bb();_.qb=_.cb();rb=function(){var a=_.m.document;return a?a.documentMode:void 0};
a:{var tb="",ub=function(){var a=_.Oa;if(_.lb)return/rv:([^\);]+)(\)|;)/.exec(a);if(kb)return/Edge\/([\d\.]+)/.exec(a);if(_.jb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.mb)return/WebKit\/(\S+)/.exec(a);if(hb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ub&&(tb=ub?ub[1]:"");if(_.jb){var vb=rb();if(null!=vb&&vb>parseFloat(tb)){sb=String(vb);break a}}sb=tb}wb=sb;xb={};_.yb=function(a){return _.gb(xb,a,function(){return 0<=_.La(wb,a)})};var Ab=_.m.document; zb=Ab&&_.jb?rb()||("CSS1Compat"==Ab.compatMode?parseInt(wb,10):5):void 0;
var Bb=_.Xa(),Cb=$a()||_.v("iPod"),Db=_.v("iPad"),Eb=_.v("Android")&&!(_.Ya()||_.Xa()||_.v("Opera")||_.v("Silk")),Fb=_.Ya(),Gb=_.Za()&&!ab();var Hb=null;var Kb,Mb;_.w=function(){};_.Ib="function"==typeof Uint8Array;
_.A=function(a,b,c,d,e){a.a=null;b||(b=c?[c]:[]);a.l=c?String(c):void 0;a.g=0===c?-1:0;a.b=b;a:{if(b=a.b.length)if(--b,c=a.b[b],!(null===c||"object"!=typeof c||_.ma(c)||_.Ib&&c instanceof Uint8Array)){a.h=b-a.g;a.c=c;break a}a.h=Number.MAX_VALUE}a.j={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.h?(c+=a.g,a.b[c]=a.b[c]||_.Jb):(Kb(a),a.c[c]=a.c[c]||_.Jb);if(e&&e.length)for(b=0;b<e.length;b++){c=d=void 0;for(var f=a,g=e[b],h=0;h<g.length;h++){var l=g[h],t=_.y(f,l);null!=t&&(c=l,d=t,_.z(f,l,void 0))}c&&_.z(f,
c,d)}};_.Jb=[];Kb=function(a){var b=a.h+a.g;a.b[b]||(a.c=a.b[b]={})};_.y=function(a,b){if(b<a.h){b+=a.g;var c=a.b[b];return c===_.Jb?a.b[b]=[]:c}if(a.c)return c=a.c[b],c===_.Jb?a.c[b]=[]:c};_.B=function(a,b){a=_.y(a,b);return null==a?a:!!a};_.Lb=function(a,b,c){a=_.y(a,b);return null==a?c:a};_.z=function(a,b,c){b<a.h?a.b[b+a.g]=c:(Kb(a),a.c[b]=c)};_.C=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.y(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};
_.E=function(a,b,c){a.a||(a.a={});var d=c?_.D(c):c;a.a[b]=c;_.z(a,b,d)};Mb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(_.ma(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){Mb(a);return a.b};
_.w.prototype.v=_.Ib?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){if(!Hb){Hb={};for(var b=0;65>b;b++)Hb[b]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)}b=Hb;for(var c=[],d=0;d<this.length;d+=3){var e=this[d],f=d+1<this.length,g=f?this[d+1]:0,h=d+2<this.length,l=h?this[d+2]:0,t=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|l>>6;l&=63;h||(l=64,f||(g=64));c.push(b[t],b[e],b[g],b[l])}return c.join("")};try{return JSON.stringify(this.b&&_.D(this),
Nb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.b&&_.D(this),Nb)};var Nb=function(a,b){return _.ia(b)&&(isNaN(b)||Infinity===b||-Infinity===b)?String(b):b};_.w.prototype.toString=function(){Mb(this);return this.b.toString()};
_.F=function(){this.G=this.G;this.v=this.v};_.F.prototype.G=!1;_.F.prototype.$=function(){this.G||(this.G=!0,this.w())};_.I=function(a,b){_.G(a,_.sa(_.H,b))};_.G=function(a,b,c){a.G?_.n(c)?b.call(c):b():(a.v||(a.v=[]),a.v.push(_.n(c)?(0,_.q)(b,c):b))};_.F.prototype.w=function(){if(this.v)for(;this.v.length;)this.v.shift()()};_.H=function(a){a&&"function"==typeof a.$&&a.$()};
var Ob=function(a,b){this.g=a;this.c=b;this.b=0;this.a=null};Ob.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.g();return a};var Pb=function(a,b){a.c(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var Tb;_.Qb=[];_.Rb=[];_.Sb=!1;Tb=function(a){_.Qb[_.Qb.length]=a;if(_.Sb)for(var b=0;b<_.Rb.length;b++)a((0,_.q)(_.Rb[b].b,_.Rb[b]))};var Ub,Wb,Xb,Vb;Ub=function(a){_.m.setTimeout(function(){throw a;},0)};_.Yb=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));c=Vb(c);!_.oa(_.m.setImmediate)||_.m.Window&&_.m.Window.prototype&&!_.v("Edge")&&_.m.Window.prototype.setImmediate==_.m.setImmediate?(Wb||(Wb=Xb()),Wb(c)):_.m.setImmediate(c)};
Xb=function(){var a=_.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.v("Presto")&&(a=function(){var e=document.createElement("IFRAME");e.style.display="none";e.src="";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write("");e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=(0,_.q)(function(l){if(("*"==h||l.origin==h)&&
l.data==g)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!_.Wa()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.n(c.next)){c=c.next;var e=c.qb;c.qb=null;e()}};return function(e){d.next={qb:e};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(e){var f=document.createElement("SCRIPT");f.onreadystatechange= function(){f.onreadystatechange=null;f.parentNode.removeChild(f);f=null;e();e=null};document.documentElement.appendChild(f)}:function(e){_.m.setTimeout(e,0)}};Vb=function(a){return a};Tb(function(a){Vb=a});
var Zb=function(){this.b=this.a=null},ac=new Ob(function(){return new $b},function(a){a.reset()});Zb.prototype.add=function(a,b){var c=ac.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Zb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var $b=function(){this.next=this.b=this.a=null};$b.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};$b.prototype.reset=function(){this.next=this.b=this.a=null};
var fc=function(a,b){bc||cc();dc||(bc(),dc=!0);ec.add(a,b)},bc,cc=function(){if(_.m.Promise&&_.m.Promise.resolve){var a=_.m.Promise.resolve(void 0);bc=function(){a.then(gc)}}else bc=function(){_.Yb(gc)}},dc=!1,ec=new Zb,gc=function(){for(var a;a=ec.remove();){try{a.a.call(a.b)}catch(b){Ub(b)}Pb(ac,a)}dc=!1};
var hc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var kc,lc,mc,rc,vc,wc,uc,sc;_.jc=function(a){this.a=0;this.j=void 0;this.c=this.b=this.g=null;this.h=this.v=!1;if(a!=_.ka)try{var b=this;a.call(void 0,function(c){_.ic(b,2,c)},function(c){_.ic(b,3,c)})}catch(c){_.ic(this,3,c)}};kc=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};kc.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};lc=new Ob(function(){return new kc},function(a){a.reset()});mc=function(a,b,c){var d=lc.get();d.h=a;d.b=b;d.c=c;return d};
_.oc=function(){var a,b=new _.jc(function(c){a=c});return new nc(b,a)};_.jc.prototype.then=function(a,b,c){return _.pc(this,_.oa(a)?a:null,_.oa(b)?b:null,c)};_.jc.prototype.$goog_Thenable=!0;_.jc.prototype.cancel=function(a){0==this.a&&fc(function(){var b=new qc(a);rc(this,b)},this)};
rc=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.g||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?rc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):sc(c),tc(c,e,3,b)))}a.g=null}else _.ic(a,3,b)};vc=function(a,b){a.b||2!=a.a&&3!=a.a||uc(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.pc=function(a,b,c,d){var e=mc(null,null,null);e.a=new _.jc(function(f,g){e.h=b?function(h){try{var l=b.call(d,h);f(l)}catch(t){g(t)}}:f;e.b=c?function(h){try{var l=c.call(d,h);!_.n(l)&&h instanceof qc?g(h):f(l)}catch(t){g(t)}}:g});e.a.g=a;vc(a,e);return e.a};_.jc.prototype.m=function(a){this.a=0;_.ic(this,2,a)};_.jc.prototype.o=function(a){this.a=0;_.ic(this,3,a)};
_.ic=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("d"));a.a=1;a:{var d=c,e=a.m,f=a.o;if(d instanceof _.jc){vc(d,mc(e||_.ka,f||null,a));var g=!0}else if(hc(d))d.then(e,f,a),g=!0;else{if(_.pa(d))try{var h=d.then;if(_.oa(h)){wc(d,h,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||(a.j=c,a.a=b,a.g=null,uc(a),3!=b||c instanceof qc||xc(a,c))}};wc=function(a,b,c,d,e){var f=!1,g=function(l){f||(f=!0,c.call(e,l))},h=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,h)}catch(l){h(l)}};
uc=function(a){a.v||(a.v=!0,fc(a.l,a))};sc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.jc.prototype.l=function(){for(var a;a=sc(this);)tc(this,a,this.a,this.j);this.v=!1};
var tc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,yc(b,c,d);else try{b.g?b.h.call(b.c):yc(b,c,d)}catch(e){zc.call(null,e)}Pb(lc,b)},yc=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},xc=function(a,b){a.h=!0;fc(function(){a.h&&zc.call(null,b)})},zc=Ub,qc=function(a){_.ua.call(this,a)};_.r(qc,_.ua);qc.prototype.name="cancel";var nc=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.Ac=function(a){this.l=[];this.D=a;this.v=this.c=!1;this.h=void 0;this.F=this.N=this.o=!1;this.m=0;this.a=null;this.j=0};_.Ac.prototype.cancel=function(a){if(this.c)this.h instanceof _.Ac&&this.h.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.j--,0>=b.j&&b.cancel())}this.D?this.D.call(null,this):this.F=!0;this.c||this.B(new _.Bc(this))}};_.Ac.prototype.I=function(a,b){this.o=!1;Cc(this,a,b)};
var Cc=function(a,b,c){a.c=!0;a.h=c;a.v=!b;Dc(a)},Fc=function(a){if(a.c){if(!a.F)throw new Ec(a);a.F=!1}};_.Ac.prototype.g=function(a){Fc(this);Cc(this,!0,a)};_.Ac.prototype.B=function(a){Fc(this);Cc(this,!1,a)};_.Hc=function(a,b,c){_.Gc(a,b,null,c)};_.Gc=function(a,b,c,d){a.l.push([b,c,d]);a.c&&Dc(a)};_.Ac.prototype.then=function(a,b,c){var d,e,f=new _.jc(function(g,h){d=g;e=h});_.Gc(this,d,function(g){g instanceof _.Bc?f.cancel():e(g)});return f.then(a,b,c)};_.Ac.prototype.$goog_Thenable=!0;
_.Ac.prototype.b=function(a){var b=new _.Ac;_.Gc(this,b.g,b.B,b);a&&(b.a=this,this.j++);return b};_.Ac.prototype.isError=function(a){return a instanceof Error};
var Ic=function(a){return(0,_.ya)(a.l,function(b){return _.oa(b[1])})},Dc=function(a){if(a.m&&a.c&&Ic(a)){var b=a.m,c=Jc[b];c&&(_.m.clearTimeout(c.a),delete Jc[b]);a.m=0}a.a&&(a.a.j--,delete a.a);b=a.h;for(var d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),f=e[0],g=e[1];e=e[2];if(f=a.v?g:f)try{var h=f.call(e||null,b);_.n(h)&&(a.v=a.v&&(h==b||a.isError(h)),a.h=b=h);if(hc(b)||"function"===typeof _.m.Promise&&b instanceof _.m.Promise)d=!0,a.o=!0}catch(l){b=l,a.v=!0,Ic(a)||(c=!0)}}a.h=b;d&&(h=(0,_.q)(a.I,
a,!0),d=(0,_.q)(a.I,a,!1),b instanceof _.Ac?(_.Gc(b,h,d),b.N=!0):b.then(h,d));c&&(b=new Kc(b),Jc[b.a]=b,a.m=b.a)},Ec=function(){_.ua.call(this)};_.r(Ec,_.ua);Ec.prototype.message="Deferred has already fired";Ec.prototype.name="AlreadyCalledError";_.Bc=function(){_.ua.call(this)};_.r(_.Bc,_.ua);_.Bc.prototype.message="Deferred was canceled";_.Bc.prototype.name="CanceledError";var Kc=function(a){this.a=_.m.setTimeout((0,_.q)(this.g,this),0);this.b=a}; Kc.prototype.g=function(){delete Jc[this.a];throw this.b;};var Jc={};
var Lc=!_.lb&&!_.jb||_.jb&&9<=Number(zb)||_.lb&&_.yb("1.9.1");_.Mc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.Oc=function(){this.b="";this.g=_.Nc};_.Oc.prototype.Da=!0;_.Oc.prototype.Aa=function(){return this.b.toString()};_.Oc.prototype.jb=!0;_.Oc.prototype.a=function(){return 1};_.Nc={};_.Pc=function(a){var b=new _.Oc;b.b=a;return b};_.Pc("about:blank");var Qc;_.Rc=function(){this.b="";this.c=Qc;this.g=null};_.Rc.prototype.jb=!0;_.Rc.prototype.a=function(){return this.g};_.Rc.prototype.Da=!0;_.Rc.prototype.Aa=function(){return this.b.toString()};_.Sc=function(a){if(a instanceof _.Rc&&a.constructor===_.Rc&&a.c===Qc)return a.b;_.la(a);return"type_error:SafeHtml"};Qc={};_.Tc=function(a,b){var c=new _.Rc;c.b=a;c.g=b;return c};_.Tc("<!DOCTYPE html>",0);_.Uc=_.Tc("",0);_.Vc=_.Tc("<br>",0);
_.Wc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.Sc(_.Uc);return!b.parentElement});
var Zc;_.Yc=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Xc(c,"*",a,b)[0]||null}return a||null};
_.Xc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&_.Ba(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a};
_.$c=function(a,b){_.Ra(b,function(c,d){c&&"object"==typeof c&&c.Da&&(c=c.Aa());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Zc.hasOwnProperty(d)?a.setAttribute(Zc[d],c):_.Ga(d,"aria-")||_.Ga(d,"data-")?a.setAttribute(d,c):a[d]=c})};Zc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.ad=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.bd=function(a){this.a=a||_.m.document||document};_.bd.prototype.C=function(a){return _.p(a)?this.a.getElementById(a):a};_.bd.prototype.setProperties=_.$c;_.cd=function(a,b){return a.a.createElement(String(b))};_.bd.prototype.getChildren=function(a){return Lc&&void 0!=a.children?a.children:(0,_.wa)(a.childNodes,function(b){return 1==b.nodeType})};
_.bd.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var ed,dd,hd,id,gd;_.fd=function(a){var b=[];dd(new ed,a,b);return b.join("")};ed=function(){};
dd=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ma(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),dd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),gd(d,c),c.push(":"),dd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":gd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("e`"+typeof b);}}};hd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};id=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;gd=function(a,b){b.push('"',a.replace(id,function(c){var d=hd[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),hd[c]=d);return d}),'"')};
var jd="StopIteration"in _.m?_.m.StopIteration:{message:"StopIteration",stack:""},kd=function(){};kd.prototype.next=function(){throw jd;};kd.prototype.ha=function(){return this};
var ld=function(a){if(a instanceof kd)return a;if("function"==typeof a.ha)return a.ha(!1);if(_.na(a)){var b=0,c=new kd;c.next=function(){for(;;){if(b>=a.length)throw jd;if(b in a)return a[b++];b++}};return c}throw Error("f");},md=function(a,b){if(_.na(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==jd)throw c;}else{a=ld(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==jd)throw c;}}},nd=function(a){if(_.na(a))return _.Fa(a);a=ld(a);var b=[];md(a,function(c){b.push(c)});return b};
_.J=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.J)for(c=a.X(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.J.prototype.T=function(){od(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.X=function(){od(this);return this.a.concat()};_.qd=function(a,b){return pd(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.J.prototype.remove=function(a){return pd(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&od(this),!0):!1};var od=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];pd(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],pd(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return pd(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){pd(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.X(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ha=function(a){od(this);var b=0,c=this.c,d=this,e=new kd;e.next=function(){if(c!=d.c)throw Error("g");if(b>=d.a.length)throw jd;var f=d.a[b++];return a?f:d.b[f]};return e};var pd=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.K=function(a,b){this.type="undefined"!=typeof _.rd&&a instanceof _.rd?String(a):a;this.b=this.target=b;this.g=!1;this.wb=!0};_.K.prototype.h=function(){this.g=!0};_.K.prototype.c=function(){this.wb=!1};var sd=!_.jb||9<=Number(zb),td=_.jb&&!_.yb("9"),ud=function(){if(!_.m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.m.addEventListener("test",_.ka,b),_.m.removeEventListener("test",_.ka,b)}catch(c){}return a}();
var wd=function(a,b){_.K.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;(b=a.relatedTarget)?_.lb&&(_.fb(b,"nodeName")||(b=null)):"mouseover"==c?
b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=_.p(a.pointerType)?a.pointerType:vd[a.pointerType]||"";this.a=a;a.defaultPrevented&&this.c()}};_.r(wd,_.K);var vd={2:"touch",3:"pen",4:"mouse"};wd.prototype.h=function(){wd.A.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0}; wd.prototype.c=function(){wd.A.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,td)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var xd,zd;xd="closure_listenable_"+(1E6*Math.random()|0);_.yd=function(a){return!(!a||!a[xd])};zd=0;var Ad=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ma=e;this.key=++zd;this.removed=this.Ka=!1},Bd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ma=null};var Cd=function(a){this.src=a;this.a={};this.b=0},Gd,Dd;Cd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Dd(a,b,d,e);-1<g?(b=a[g],c||(b.Ka=!1)):(b=new Ad(b,this.src,f,!!d,e),b.Ka=c,a.push(b));return b};Cd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Dd(e,b,c,d);return-1<b?(Bd(e[b]),_.Ca(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var Ed=function(a,b){var c=b.type;c in a.a&&_.Da(a.a[c],b)&&(Bd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};Cd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Bd(d[e]);delete this.a[c];this.b--}return b};_.Fd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Dd(a,c,d,e));return-1<b?a[b]:null};
Gd=function(a){var b=_.n(void 0)?"undefined":void 0,c=_.n(b),d=c?b.toString():"",e=_.n(void 0);return Sa(a.a,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&void 0!=f[g].capture))return!0;return!1})};Dd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ma==d)return e}return-1};
var Hd,Id,Jd,Nd,Pd,Qd,Vd,Ud,Rd,Wd;Hd="closure_lm_"+(1E6*Math.random()|0);Id={};Jd=0;_.Ld=function(a,b,c,d,e){if(d&&d.once)return _.Kd(a,b,c,d,e);if(_.ma(b)){for(var f=0;f<b.length;f++)_.Ld(a,b[f],c,d,e);return null}c=_.Md(c);return _.yd(a)?a.listen(b,c,_.pa(d)?!!d.capture:!!d,e):Nd(a,b,c,!1,d,e)};
Nd=function(a,b,c,d,e,f){if(!b)throw Error("h");var g=_.pa(e)?!!e.capture:!!e,h=_.Od(a);h||(a[Hd]=h=new Cd(a));c=h.add(b,c,d,g,f);if(c.proxy)return c;d=Pd();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)ud||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Qd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("i");Jd++;return c};
Pd=function(){var a=Rd,b=sd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};_.Kd=function(a,b,c,d,e){if(_.ma(b)){for(var f=0;f<b.length;f++)_.Kd(a,b[f],c,d,e);return null}c=_.Md(c);return _.yd(a)?a.N(b,c,_.pa(d)?!!d.capture:!!d,e):Nd(a,b,c,!0,d,e)};
_.Sd=function(a,b,c,d,e){if(_.ma(b))for(var f=0;f<b.length;f++)_.Sd(a,b[f],c,d,e);else d=_.pa(d)?!!d.capture:!!d,c=_.Md(c),_.yd(a)?a.g.remove(String(b),c,d,e):a&&(a=_.Od(a))&&(b=_.Fd(a,b,c,d,e))&&_.Td(b)};
_.Td=function(a){if(!_.ia(a)&&a&&!a.removed){var b=a.src;if(_.yd(b))Ed(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Qd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Jd--;(c=_.Od(b))?(Ed(c,a),0==c.b&&(c.src=null,b[Hd]=null)):Bd(a)}}};Qd=function(a){return a in Id?Id[a]:Id[a]="on"+a};
Vd=function(a,b,c,d){var e=!0;if(a=_.Od(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=Ud(f,d),e=e&&!1!==f)}return e};Ud=function(a,b){var c=a.listener,d=a.Ma||a.src;a.Ka&&_.Td(a);return c.call(d,b)};
Rd=function(a,b){if(a.removed)return!0;if(!sd){var c=b||_.ja("window.event");b=new wd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.g&&0<=e;e--){b.b=c[e];var f=Vd(c[e],a,!0,b);d=d&&f}for(e=0;!b.g&&e<c.length;e++)b.b=c[e],f=Vd(c[e],a,!1,b),d=d&&f}return d}return Ud(a,new wd(b,this))}; _.Od=function(a){a=a[Hd];return a instanceof Cd?a:null};Wd="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Md=function(a){if(_.oa(a))return a;a[Wd]||(a[Wd]=function(b){return a.handleEvent(b)});return a[Wd]};Tb(function(a){Rd=a(Rd)});
_.L=function(){_.F.call(this);this.g=new Cd(this);this.ga=this;this.F=null};_.r(_.L,_.F);_.L.prototype[xd]=!0;_.L.prototype.I=function(a){this.F=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.Sd(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.ga;d=b.type||b;if(_.p(b))b=new _.K(b,a);else if(b instanceof _.K)b.target=b.target||a;else{var e=b;b=new _.K(d,a);_.Va(b,e)}e=!0;if(c)for(var f=c.length-1;!b.g&&0<=f;f--){var g=b.b=c[f];e=g.na(d,!0,b)&&e}b.g||(g=b.b=a,e=g.na(d,!0,b)&&e,b.g||(e=g.na(d,!1,b)&&e));if(c)for(f=0;!b.g&&f<c.length;f++)g=b.b=c[f],e=g.na(d,!1,b)&&e;return e};_.L.prototype.w=function(){_.L.A.w.call(this);this.g&&this.g.removeAll(void 0);this.F=null};
_.L.prototype.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};_.L.prototype.N=function(a,b,c,d){return this.g.add(String(a),b,!0,c,d)};_.L.prototype.na=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var g=f.listener,h=f.Ma||f.src;f.Ka&&Ed(this.g,f);d=!1!==g.call(h,c)&&d}}return d&&0!=c.wb};
var Xd=function(){};Xd.prototype.a=null;var Zd=function(a){var b;(b=a.a)||(b={},Yd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var $d,ae=function(){};_.r(ae,Xd);var be=function(a){return(a=Yd(a))?new ActiveXObject(a):new XMLHttpRequest},Yd=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("j");}return a.b};$d=new ae;
var de;_.ce=function(a){if(a.T&&"function"==typeof a.T)return a.T();if(_.p(a))return a.split("");if(_.na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};
de=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.na(a)||_.p(a))(0,_.u)(a,b,void 0);else{if(a.X&&"function"==typeof a.X)var c=a.X();else if(a.T&&"function"==typeof a.T)c=void 0;else if(_.na(a)||_.p(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=_.ce(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.ee=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.m;this.c=(0,_.q)(this.kc,this);this.h=(0,_.ha)()};_.r(_.ee,_.L);_.k=_.ee.prototype;_.k.pa=!1;_.k.Y=null;_.k.setInterval=function(a){this.b=a;this.Y&&this.pa?(this.stop(),this.start()):this.Y&&this.stop()};_.k.kc=function(){if(this.pa){var a=(0,_.ha)()-this.h;0<a&&a<.8*this.b?this.Y=this.a.setTimeout(this.c,this.b-a):(this.Y&&(this.a.clearTimeout(this.Y),this.Y=null),_.M(this,"tick"),this.pa&&(this.stop(),this.start()))}};
_.k.start=function(){this.pa=!0;this.Y||(this.Y=this.a.setTimeout(this.c,this.b),this.h=(0,_.ha)())};_.k.stop=function(){this.pa=!1;this.Y&&(this.a.clearTimeout(this.Y),this.Y=null)};_.k.w=function(){_.ee.A.w.call(this);this.stop();delete this.a};_.fe=function(a,b,c){if(_.oa(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("k");return 2147483647<Number(b)?-1:_.m.setTimeout(a,b||0)};_.ge=function(a){_.m.clearTimeout(a)};
var he=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,ie=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var je=function(a){_.L.call(this);this.headers=new _.J;this.o=a||null;this.b=!1;this.m=this.a=null;this.K="";this.c=this.D=this.h=this.B=!1;this.l=0;this.j=null;this.V="";this.O=this.M=!1},ke,le,me,ue,te,qe,ve;_.r(je,_.L);ke=/^https?$/i;le=["POST","PUT"];me=[];_.ne=function(a,b,c,d,e,f,g){var h=new je;me.push(h);b&&h.listen("complete",b);h.N("ready",h.ba);f&&(h.l=Math.max(0,f));g&&(h.M=g);h.send(a,c,d,e)};je.prototype.ba=function(){this.$();_.Da(me,this)};
je.prototype.send=function(a,b,c,d){if(this.a)throw Error("l`"+this.K+"`"+a);b=b?b.toUpperCase():"GET";this.K=a;this.B=!1;this.b=!0;this.a=this.o?be(this.o):be($d);this.m=this.o?Zd(this.o):Zd($d);this.a.onreadystatechange=(0,_.q)(this.U,this);try{this.D=!0,this.a.open(b,String(a),!0),this.D=!1}catch(f){oe(this);return}a=c||"";var e=new _.J(this.headers);d&&de(d,function(f,g){e.set(g,f)});d=_.Aa(e.X(),pe);c=_.m.FormData&&a instanceof _.m.FormData;!_.Ba(le,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(f,g){this.a.setRequestHeader(g,f)},this);this.V&&(this.a.responseType=this.V);"withCredentials"in this.a&&this.a.withCredentials!==this.M&&(this.a.withCredentials=this.M);try{qe(this),0<this.l&&((this.O=re(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.q)(this.S,this)):this.j=_.fe(this.S,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){oe(this)}};var re=function(a){return _.jb&&_.yb(9)&&_.ia(a.timeout)&&_.n(a.ontimeout)},pe=function(a){return"content-type"==a.toLowerCase()};
je.prototype.S=function(){"undefined"!=typeof _.da&&this.a&&(_.M(this,"timeout"),this.abort(8))};var oe=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);se(a);te(a)},se=function(a){a.B||(a.B=!0,_.M(a,"complete"),_.M(a,"error"))};je.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.M(this,"complete"),_.M(this,"abort"),te(this))};je.prototype.w=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),te(this,!0));je.A.w.call(this)};
je.prototype.U=function(){this.G||(this.D||this.h||this.c?ue(this):this.L())};je.prototype.L=function(){ue(this)};ue=function(a){if(a.b&&"undefined"!=typeof _.da&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=ve(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.fe(a.U,0,a);else if(_.M(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.we(a)?(_.M(a,"complete"),_.M(a,"success")):se(a)}finally{te(a)}}};
te=function(a,b){if(a.a){qe(a);var c=a.a,d=a.m[0]?_.ka:null;a.a=null;a.m=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};qe=function(a){a.a&&a.O&&(a.a.ontimeout=null);a.j&&(_.ge(a.j),a.j=null)};
_.we=function(a){var b=ve(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.K).match(he)[1]||null,!a&&_.m.self&&_.m.self.location&&(a=_.m.self.location.protocol,a=a.substr(0,a.length-1)),b=!ke.test(a?a.toLowerCase():"");c=b}return c};ve=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};Tb(function(a){je.prototype.L=a(je.prototype.L)});
var ye;_.N=function(a){_.F.call(this);this.O=a;this.o={}};_.r(_.N,_.F);var xe=[];_.N.prototype.listen=function(a,b,c,d){_.ma(b)||(b&&(xe[0]=b.toString()),b=xe);for(var e=0;e<b.length;e++){var f=_.Ld(a,b[e],c||this.handleEvent,d||!1,this.O||this);if(!f)break;this.o[f.key]=f}return this};_.ze=function(a,b,c,d){ye(a,b,c,d,void 0)};ye=function(a,b,c,d,e,f){if(_.ma(c))for(var g=0;g<c.length;g++)ye(a,b,c[g],d,e,f);else(b=_.Kd(b,c,d||a.handleEvent,e,f||a.O||a))&&(a.o[b.key]=b)}; _.N.prototype.removeAll=function(){_.Ra(this.o,function(a,b){this.o.hasOwnProperty(b)&&_.Td(a)},this);this.o={}};_.N.prototype.w=function(){_.N.A.w.call(this);this.removeAll()};_.N.prototype.handleEvent=function(){throw Error("m");};
_.Ae=function(a){_.A(this,a,0,null,null)};_.r(_.Ae,_.w);var Ce=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("n");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,f,g,h,l,t,x,O){if("%"==t)return"%";var fa=c.shift();if("undefined"==typeof fa)throw Error("o");arguments[0]=fa;return Be[t].apply(null,arguments)})},Be={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Ma(" ",Number(c)-a.length):Ma(" ",Number(c)-a.length)+a},f:function(a,b,
c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ma(" ",a):f+Ma(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,h){return Be.f(parseInt(a,10),b,c,d,0,f,g,h)}};Be.i=Be.d;Be.u=Be.d;
_.P=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Ce("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+Ce(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Ce.apply({},c)))};
_.Ee=function(a){_.A(this,a,"h_exts",De,null)};_.r(_.Ee,_.w);var De=[2];_.Ee.messageId="h_exts";var Fe,Ge,He,Ke,Me,Xe,Ne,Pe,Oe,Se,Qe,Le,Ye;_.Q=function(a,b){this.b=this.j=this.h="";this.c=null;this.l=this.a="";this.v=!1;var c;a instanceof _.Q?(this.v=_.n(b)?b:a.v,Fe(this,a.h),this.j=a.j,this.b=a.b,Ge(this,a.c),this.a=a.a,He(this,Ie(a.g)),_.Je(this,a.l)):a&&(c=String(a).match(he))?(this.v=!!b,Fe(this,c[1]||"",!0),this.j=Ke(c[2]||""),this.b=Ke(c[3]||"",!0),Ge(this,c[4]),this.a=Ke(c[5]||"",!0),He(this,c[6]||"",!0),_.Je(this,c[7]||"",!0)):(this.v=!!b,this.g=new Le(null,this.v))};
_.Q.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Me(b,Ne,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Me(b,Ne,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Me(c,"/"==c.charAt(0)?Oe:Pe,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",Me(c,Qe));return a.join("")};
Fe=function(a,b,c){a.h=c?Ke(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};Ge=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("p`"+b);a.c=b}else a.c=null};He=function(a,b,c){b instanceof Le?(a.g=b,Re(a.g,a.v)):(c||(b=Me(b,Se)),a.g=new Le(b,a.v))};_.R=function(a,b,c){a.g.set(b,c)};_.Je=function(a,b,c){a.l=c?Ke(b):b};_.Te=function(a){return a instanceof _.Q?new _.Q(a):new _.Q(a,void 0)};
_.Ue=function(a,b){a instanceof _.Q||(a=_.Te(a));b instanceof _.Q||(b=_.Te(b));var c=a;a=new _.Q(c);var d=!!b.h;d?Fe(a,b.h):d=!!b.j;d?a.j=b.j:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)Ge(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){c=_.Ga(e,"/");e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];"."==h?c&&g==e.length&&f.push(""):".."==h?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&g==e.length&&f.push("")):(f.push(h),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?He(a,Ie(b.g)):d=!!b.l;d&&_.Je(a,b.l);return a};Ke=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""};Me=function(a,b,c){return _.p(a)?(a=encodeURI(a).replace(b,Xe),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Xe=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Ne=/[#\/\?@]/g;Pe=/[#\?:]/g;Oe=/[#\?]/g;
Se=/[#\?@]/g;Qe=/#/g;Le=function(a,b){this.b=this.a=null;this.g=a||null;this.c=!!b};Ye=function(a){a.a||(a.a=new _.J,a.b=0,a.g&&ie(a.g,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Le.prototype.add=function(a,b){Ye(this);this.g=null;a=Ze(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};Le.prototype.remove=function(a){Ye(this);a=Ze(this,a);return _.qd(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};
Le.prototype.clear=function(){this.a=this.g=null;this.b=0};var $e=function(a,b){Ye(a);b=Ze(a,b);return _.qd(a.a,b)};_.k=Le.prototype;_.k.forEach=function(a,b){Ye(this);this.a.forEach(function(c,d){(0,_.u)(c,function(e){a.call(b,e,d,this)},this)},this)};_.k.X=function(){Ye(this);for(var a=this.a.T(),b=this.a.X(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
_.k.T=function(a){Ye(this);var b=[];if(_.p(a))$e(this,a)&&(b=_.Ea(b,this.a.get(Ze(this,a))));else{a=this.a.T();for(var c=0;c<a.length;c++)b=_.Ea(b,a[c])}return b};_.k.set=function(a,b){Ye(this);this.g=null;a=Ze(this,a);$e(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};_.k.get=function(a,b){if(!a)return b;a=this.T(a);return 0<a.length?String(a[0]):b};_.af=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Ze(a,b),_.Fa(c)),a.b+=c.length)};
Le.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.X(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.T(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.g=a.join("&")};
var Ie=function(a){var b=new Le;b.g=a.g;a.a&&(b.a=new _.J(a.a),b.b=a.b);return b},Ze=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Re=function(a,b){b&&!a.c&&(Ye(a),a.g=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(this.remove(d),_.af(this,e,c))},a));a.c=b};
var bf;bf=function(a){return(a=a.exec(_.Oa))?a[1]:""};_.cf=function(){if(Bb)return bf(/Firefox\/([0-9.]+)/);if(_.jb||kb||hb)return wb;if(Fb)return ab()?bf(/CriOS\/([0-9.]+)/):bf(/Chrome\/([0-9.]+)/);if(Gb&&!ab())return bf(/Version\/([0-9.]+)/);if(Cb||Db){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Oa);if(a)return a[1]+"."+a[2]}else if(Eb)return(a=bf(/Android\s+([0-9.]+)/))?a:bf(/Version\/([0-9.]+)/);return""}();
var df=function(a,b){_.K.call(this,a,b);this.W=b};_.r(df,_.K);var ef=function(a){_.A(this,a,"capi_md1571",null,null)};_.r(ef,_.w);var ff=function(a){_.A(this,a,0,null,null)};_.r(ff,_.w);ef.messageId="capi_md1571";var hf=function(){for(var a=10,b=gf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},gf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.jf=function(a,b){_.F.call(this);this.j=b||hf();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.N(this);_.I(this,this.h);this.h.listen(window,"message",this.m)};_.r(_.jf,_.F);_.jf.prototype.da=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.jf.prototype.m=function(a){a=a.a;var b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.Q(b)).b,b=_.Ha(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.p(b)&&"["==b[0]){try{var c=JSON.parse(b);if(!_.ma(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new ef(c),_.y(c,1)==this.j)){b=_.y(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.da(a.origin,a.source);1==
_.y(c,2)?this.send(2):this.l(c,a)}}};_.jf.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new ef;_.z(b,3,this.j);_.z(b,1,this.a);_.z(b,2,a);var d=JSON.stringify(_.D(b)),e=this.g,f=this.c;_.jb?_.fe(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var kf=function(a,b,c,d){this.g=_.oc();this.a=new _.jf((0,_.q)(this.h,this),c);this.a.da("*",a,d);this.a.a=b;this.b=new _.ee(50);this.b.start();_.Ld(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.v;b=mc(b,b,this);b.g=!0;vc(a,b)};kf.prototype.v=function(){_.H(this.a);_.Sd(this.b,"tick",this.c,!1,this);_.H(this.b)};kf.prototype.c=function(){this.a.send(1)};kf.prototype.h=function(a,b){2==_.y(a,2)&&this.g.b(b.origin)};
var lf=function(a,b,c){_.F.call(this);this.b=a;a=_.y(b,3);b=_.y(b,1);this.a=new _.jf((0,_.q)(this.g,this),b);this.a.a=a;c&&this.a.da(c.origin,c.source);_.I(this,this.a)};_.r(lf,_.F);lf.prototype.send=function(a){var b=new ef;_.E(b,4,a);this.a.send(0,b)};lf.prototype.connect=function(a,b){this.a.da(a,b);this.a.send(3)};lf.prototype.g=function(a){0==_.y(a,2)&&(a=_.C(a,ff,4),this.b(a))};lf.prototype.c=_.ka;
var nf=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],mf(this)):(this.a=new _.jf(_.ka,_.y(b,1)),a=_.y(b,3),this.a.a=a)};_.r(nf,_.F);nf.prototype.w=function(){nf.A.w.call(this);this.b&&this.b.close();_.H(this.a)};nf.prototype.c=function(){this.g=new _.N(this);_.I(this,this.g);mf(this)};nf.prototype.send=function(a){this.b.postMessage(_.D(a))};
nf.prototype.connect=function(a,b){var c=new MessageChannel;this.b=c.port1;mf(this);var d=this.a;this.a=null;c=c.port2;d.da(a,b);d.send(4,void 0,[c]);_.H(d)};var mf=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};nf.prototype.j=function(a){a=a.a;try{var b=new ff(a.data)}catch(c){return}this.h(b)};
var of=function(a,b,c){var d=!1;_.n(_.y(b,2))?4==_.y(b,2)&&(d=!0):d=Fb;return d?new nf(a,b,c):new lf(a,b,c)};var tf,vf;_.pf=function(){_.L.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.G(this,this.o,this);this.b=null};_.r(_.pf,_.L);_.pf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.rf=function(a){a.o();a.h=[];a.b=new _.Ac;a.c.push((0,_.q)(a.b.cancel,a.b));a.l=!1;_.Hc(a.b.b(),function(b){(Gd(this.g)||this.F)&&_.qf(this);this.c.push(_.sa(_.H,b))},a)};_.pf.prototype.sendMessage=function(a){sf(this,_.D(a))};var sf=function(a,b){if(a.b){var c=new ff;_.z(c,1,b);_.Hc(a.b.b(),function(d){d.send(c)})}};
_.pf.prototype.H=function(){return this};_.pf.prototype.da=function(a,b,c){this.a.da(a,b,c)};_.uf=function(a,b,c,d){_.rf(a);tf(a,b,c,d).then(function(e){var f=new ef;_.z(f,1,e.lc);_.z(f,3,c);f=of((0,_.q)(this.m,this),f);f.connect(e.origin,b);this.b.g(f)},void 0,a)};tf=function(a,b,c,d){var e=hf();b=(new kf(b,c,e,d)).g.a;a.c.push((0,_.q)(b.cancel,b));return b.then(function(f){return{lc:e,origin:f}})};
_.pf.prototype.D=function(a,b){if(3==_.y(a,2)||4==_.y(a,2))_.H(this.a),this.a=null,this.b.g(of((0,_.q)(this.m,this),a,b))};_.pf.prototype.m=function(a){this.h.push(a);this.B()};_.pf.prototype.B=function(){for(;vf(this););};vf=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.y(a.h.shift(),1);a.j&&sf(a.j,b);_.M(a,new df(b[0],b));return!0};_.qf=function(a){a.l||(a.l=!0,a.b&&_.Hc(a.b.b(),function(b){b.c();_.fe(this.B,0,this)},a))}; _.pf.prototype.listen=function(a,b,c,d){_.qf(this);return _.pf.A.listen.call(this,a,b,c,d)};_.pf.prototype.N=function(a,b,c,d){_.qf(this);return _.pf.A.N.call(this,a,b,c,d)};_.pf.prototype.I=function(a){_.qf(this);return _.pf.A.I.call(this,a)};
var wf=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};wf.prototype.ca=function(a){this.c=a;return this};wf.prototype.qa=function(a){this.a=a;return this};wf.prototype.mb=function(a){this.g=_.Ta(a);return this};var xf=function(){};var yf=function(){};_.r(yf,xf);yf.prototype.clear=function(){var a=nd(this.ha(!0)),b=this;(0,_.u)(a,function(c){b.remove(c)})};var zf=function(a){this.a=a};_.r(zf,yf);_.k=zf.prototype;_.k.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.k.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.k.get=function(a){a=this.a.getItem(a);if(!_.p(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.k.remove=function(a){this.a.removeItem(a)};
_.k.ha=function(a){var b=0,c=this.a,d=new kd;d.next=function(){if(b>=c.length)throw jd;var e=c.key(b++);if(a)return e;e=c.getItem(e);if(!_.p(e))throw"Storage mechanism: Invalid value was encountered";return e};return d};_.k.clear=function(){this.a.clear()};_.k.key=function(a){return this.a.key(a)};
var Af=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.r(Af,zf);var Cf=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new Af);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=JSON.parse(a)||[]}catch(c){}a=!1;_.ma(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&Bf(this)},Bf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.fd(a.a))}catch(b){}};
var Df=function(a){_.F.call(this);this.a=a;this.h=!1};_.r(Df,_.F);Df.prototype.setEnabled=function(a){this.h=a};var S=function(a){Df.call(this,a);this.o=100;this.m={};this.P=null;this.g="";this.F=!0;this.j=10;this.b=null;this.c=!1};_.r(S,Df);S.prototype.Ab=function(a){this.F=a;return this};S.prototype.setUseLocalStorage=S.prototype.Ab;S.prototype.jc=function(a){this.j=Math.min(a,100);return this};S.prototype.setMaxErrorsPerHour=S.prototype.jc;S.prototype.yb=function(a){this.o=a;return this};S.prototype.setGlobalSampling=S.prototype.yb;S.prototype.ob=function(a,b){this.m[a]=b;return this};
S.prototype.addPerErrorMessageSampling=S.prototype.ob;S.prototype.xb=function(a){this.P=a;return this};S.prototype.setCallback=S.prototype.xb;S.prototype.ic=function(a){this.g=a;return this};S.prototype.setClientId=S.prototype.ic;S.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.B.bind(this);this.setEnabled(!0);return!0};S.prototype.enable=S.prototype.enable;
S.prototype.ub=function(a,b,c,d,e){var f=_.Te(window.location.href);a=null!=e&&null!=e.message?e.message:a;var g;if(g=!_.oa(this.P)||this.P(f.a,a,b,c,d,e))if(g=this.c){g=Object.keys(this.m);for(var h=100,l=0;l<g.length;++l){var t=g[l];(new RegExp(t)).test(a)&&(h=this.m[t])}if(g=(100*Math.random()).toFixed(6)>=this.o*h/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new Cf(this.j,this.F));if(null===this.b)g=!1;else{a:{g=this.b;h=(0,_.ha)();if(g.a.length==g.g)if(g.a[0]<h-36E5)g.a.shift();else{g=!1;break a}g.a.push(h);
Bf(g);g=!0}g=!g}g=!g&&this.c}}g&&(g=_.Ta(this.a.g),g.url=f.a,g.type="JavascriptError",g.error_message=a,h="Other",hb?h="Opera":_.jb?h="Internet Explorer":Bb?h="Firefox":Fb?h="Chrome":Gb&&(h="Safari"),g.browser=h,g.browser_version=_.cf,g.os=_.db()?"Chrome OS":_.v("Linux")?"Linux":_.cb()?"Windows":_.v("Android")?"Android":$a()?"iPhone":_.v("iPad")?"iPad":_.v("iPod")?"iPod":_.bb()?"Mac":"Unknown",h=_.Oa,l="",_.cb()?(l=/Windows (?:NT|Phone) ([0-9.]+)/,l=(h=l.exec(h))?h[1]:"0.0"):ab()?(l=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,
l=(h=l.exec(h))&&h[1].replace(/_/g,".")):_.bb()?(l=/Mac OS X ([0-9_.]+)/,l=(h=l.exec(h))?h[1].replace(/_/g,"."):"10"):_.v("Android")?(l=/Android\s+([^\);]+)(\)|;)/,l=(h=l.exec(h))&&h[1]):_.db()&&(l=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,l=(h=l.exec(h))&&h[1]),g.os_version=l||"",null!=this.a.a&&(g.channel=this.a.a),_.Ia(this.g)||(g.guid=this.g),null!=b&&(g.src=b),null!=c&&(g.line=c),null!=d&&(g.column=d),g.prod=this.a.b,g.ver=this.a.c,c=null!=e?_.Na(e.stack):"",b=Ef(g),_.Ia(a)||(d=c.split("\n"),
-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),Ff(this,"https://clients2.google.com/cr/staging_report",b,c),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Na(this.a.a),_.Ia(a)||(f.version=a),Ff(this,"https://clients2.google.com/cr/staging_perf",Ef(f)))};S.prototype.reportError=S.prototype.ub;S.prototype.B=function(a,b,c,d,e){this.ub(a,b,c,d,e);null!=this.l&&_.oa(this.l)&&this.l(a,b,c,d,e)};
var Ef=function(a){var b="",c;for(c in a)b+=_.Ia(b)?"?":"&",b+=c+"="+encodeURIComponent(a[c]);return b},Ff=function(a,b,c,d){d=d||"";var e=_.Ia(d)?{}:{"Content-Type":"text/plain"};_.ne(b+c,a.I.bind(a,b),"POST",d,e,6E4,!0)};S.prototype.I=function(a,b){_.we(b.target)};
var Gf=function(a){Df.call(this,a);this.P=null;this.b=0};_.r(Gf,Df);Gf.prototype.xb=function(a){this.P=a;return this};var Hf=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Gf.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.ee(6E4);_.I(this,a);var b=new _.N(this);_.I(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
Gf.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<Hf.length;++b)if(this.b==Hf[b].age){a=Hf[b].name;break}if(""!=a){b=If.test(_.Oa)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Te(window.location.href).a;
c="?product="+encodeURIComponent(this.a.b)+"&url="+encodeURIComponent(b);var d=_.Na(this.a.a);_.Ia(d)||(c+="&version="+encodeURIComponent(d));for(d=0;d<a.length;++d)c+="&"+encodeURIComponent(a[d].name)+"="+a[d].value,_.oa(this.P)&&this.P(b,a[d].displayName,a[d].value);_.ne("https://clients2.google.com/cr/staging_perf"+c,Jf,"POST","",null,6E4,!0)}}};var Jf=function(a){_.we(a.target)},If=/(x86_64|Win64)/;
var Kf=function(a){_.F.call(this);this.b=new wf(a);this.a={}};_.r(Kf,_.F);_.ta("webmonitoring.Monitoring",Kf);Kf.prototype.ca=function(a){this.b.ca(a);return this};Kf.prototype.setVersion=Kf.prototype.ca;Kf.prototype.qa=function(a){this.b.qa(a);return this};Kf.prototype.setChannel=Kf.prototype.qa;Kf.prototype.mb=function(a){this.b.mb(a);return this};Kf.prototype.setContext=Kf.prototype.mb;Kf.prototype.La=function(){null!=this.a[2]||(this.a[2]=new S(this.b));return this.a[2]}; Kf.prototype.createJsErrorsReporter=Kf.prototype.La;
var Lf=function(a){Kf.call(this,a)};_.r(Lf,Kf);Lf.prototype.ca=function(a){return Lf.A.ca.call(this,a)};Lf.prototype.qa=function(a){return Lf.A.qa.call(this,a)};Lf.prototype.La=function(){var a=Lf.A.La.call(this);a.c=!0;return a};_.Mf=function(){var a=new Lf("Google_Hangouts_Chrome");a.qa(chrome.runtime.id);a.ca(chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new Gf(a.b));a.a[1].enable();a.La().Ab(!1).yb(100).ob("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
try{
var zp=function(a,b){_.pc(a,null,b,void 0)},Ap=function(a){_.A(this,a,"uv_r_hrd",null,null)};_.r(Ap,_.w);Ap.messageId="uv_r_hrd";
var Bp=function(a,b){return a.g.get(b)},Cp=function(a,b){a.j=b;_.G(a,function(){this.j=null},a);_.qf(a)},Dp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.na(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}},Ep=function(a,b,c){a=_.B(a,b);return null==a?c:a},Fp=function(a){var b=new _.pf;_.rf(b);b.a=new _.jf((0,_.q)(b.D,b),a);b.a.da("*",void 0,void 0);b.c.push(_.sa(_.H,b.a));return b};
var Gp=function(a){this.a=a;_.jb||(delete this.a.lpu,delete this.a.ppu)},Hp=["cn","tp"],Ip=function(a,b){if(_.oa(document.postMessage)||_.oa(window.postMessage)||_.jb&&window.postMessage)var c=1;else if(_.lb)c=2;else{var d;if(d=_.jb){d=!1;try{c=window.opener,window.opener={},d=_.fb(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new Gp(d)};_.ta("GTalk_IFrameChannelConfig.build",Ip);
var Jp=function(){},Mp=function(a){var b=a.ma,c=function(l){c.A.constructor.call(this,l);var t=this.Z.length;this.a=[];for(var x=0;x<t;++x)this.Z[x].Kc||(this.a[x]=new this.Z[x](l))};_.r(c,b);for(var d=[];a;){if(b=a.ma){b.Z&&Dp(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.oa(e[f])&&e[f]!==b){var g=!!e[f].Cb,h=Kp(f,e,d,g);(g=Lp(f,e,h,g))&&(c.prototype[f]=g)}}a=a.A&&a.A.constructor}c.prototype.Z=d;return c},Kp=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},Lp=function(a,b,c,d){var e;c.length?d?e=function(f){var g=this.a[c[0]];return g?g[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Eb?e=function(f){a:{var g=Array.prototype.slice.call(arguments,0);for(var h=0;h<c.length;++h){var l=this.a[c[h]];if(l=l?l[a].apply(l,g):this.Z[c[h]].prototype[a].apply(this,g)){g=l;break a}}g=!1}return g}:b[a].Db?e=function(f){a:{var g=Array.prototype.slice.call(arguments,0);for(var h=0;h<c.length;++h){var l=
this.a[c[h]];l=l?l[a].apply(l,g):this.Z[c[h]].prototype[a].apply(this,g);if(null!=l){g=l;break a}}g=void 0}return g}:b[a].Vb?e=function(f){for(var g=Array.prototype.slice.call(arguments,0),h=0;h<c.length;++h){var l=this.a[c[h]];l?l[a].apply(l,g):this.Z[c[h]].prototype[a].apply(this,g)}}:e=function(f){for(var g=Array.prototype.slice.call(arguments,0),h=[],l=0;l<c.length;++l){var t=this.a[c[l]];h.push(t?t[a].apply(t,g):this.Z[c[l]].prototype[a].apply(this,g))}return h}:d||b[a].Eb||b[a].Db||b[a].Vb? e=null:e=Np;return e},Np=function(){return[]};Jp.prototype.h=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var Op=function(a){(a?a:function(){}).Cb=!0};
var Pp=function(){};_.r(Pp,Jp);Pp.prototype.b=function(a){return a};Op(Pp.prototype.b);Pp.prototype.g=function(){return!0};Op(Pp.prototype.g);var Qp=function(a){_.A(this,a,0,null,null)};_.r(Qp,_.w);var Rp=function(a,b){var c=new Qp;_.z(c,1,b);_.z(c,2,a);return c},Sp=Rp("?",0),Tp=Rp("q",1),Up=Rp("<",2),Vp=Rp(">",3),Wp=Rp("~",4),Xp=Rp("s",5),Yp={pc:Sp,xc:Tp,rc:Up,sc:Vp,qc:Wp,yc:Xp};var Zp=function(a){_.A(this,a,"h_cc",null,null)};_.r(Zp,_.w);var $p=function(a){_.A(this,a,0,null,null)};_.r($p,_.w);var aq=function(a){_.A(this,a,0,null,null)};_.r(aq,_.w);var bq=function(a){_.A(this,a,0,null,null)};_.r(bq,_.w);var cq=function(a){_.A(this,a,0,null,null)};_.r(cq,_.w);Zp.messageId="h_cc";var dq=function(a,b){_.z(a,3,b)},eq=function(a,b){_.z(a,4,b)},fq=function(a,b){_.z(a,11,b)};
var gq=function(a){_.A(this,a,"ci:ec",null,null)};_.r(gq,_.w);gq.messageId="ci:ec";var hq=function(a){return this.hb.h(a)};var iq=function(){this.a=window.document||{cookie:""}};_.k=iq.prototype;_.k.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("C`"+a);if(/[;\r\n]/.test(b))throw Error("D`"+b);_.n(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.ha)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.k.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.Ja)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.k.remove=function(a,b,c){var d=_.n(this.get(a));this.set(a,"",0,b,c);return d};_.k.X=function(){return jq(this).keys};_.k.T=function(){return jq(this).values};_.k.clear=function(){for(var a=jq(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var jq=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.Ja)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var kq=function(a,b){if(!this.hb){for(var c=this.constructor;c&&!c.ma;)c=c.A&&c.A.constructor;c.ma.sb||(c.ma.sb=Mp(c));this.hb=new c.ma.sb(this);this.h||(this.h=hq)}var d=this.hb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ga(d,"https://talkgadget.google.com/talkgadget/")){c=(new iq).get("WCSDBG","");c=c.split(";")[0];c=c.split("|")[0];var e=["plus.google.com"],f=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<c.length&&!_.Ba(e,c)&&f.test(c)&&(d=_.Te(d),d=_.Te("https://"+
c+d.a).toString())}this.g=d;this.c=b||new gq;a.notificationsOnly&&_.z(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(b=Bp(new _.Q(window.location.href),"authuser"),null!=b&&(this.b=b));this.o=a.clientUrl||"notifierclient";b=Bp(_.Te(this.o),"authuser");null!=b&&(this.b=b);this.ab=a.propertyName||"Google Talk";this.I=a.cssUrl;this.locale=a.locale;this.j=a.debug;this.Ja=a.userJid;this.Ga=a.uiVersion;this.Nb=null!=a.rosterExpanded?a.rosterExpanded:!0;this.V=a.hostLogMinValue;this.xa=a.hideChat;
this.Fb=a.refresh;this.O=a.hideProfileCard;this.U=a.hideStatusMsgs;this.S=a.hideRosterOptions;this.M=a.hideRecentConversations;this.L=a.hideOTR;this.bb=a.hostServerMessageCallback||!1;this.ba=a.isCentralRoster;this.gb=a.isFullFrame||!1;this.Jb=a.rosterClass||"talk_roster";this.Ob=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.wa=a.parentToken;_.n(a.isRtl)||_.Mc.test(this.locale);
this.l=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var g in Yp)b.push(_.D(Yp[g]))}this.D=a.entityId;this.Ha=a.useQuasarPanels||!1;this.silent=a.silent||!1;this.fb=a.ignoreCentralRoster||!1;this.Ib=a.lazy||!1;this.Na=a.handleProfileLinks||!1;this.ga=a.hostSettings;this.m=a.screen;this.B=a.docsConfig;this.Hb=a.jsmode;this.va=a.moleWidth;this.ua=a.moleHeight;this.ta=a.minimizedMoleHeight||36;this.Qb=a.derp;this.Fa=window.location.protocol+"//"+window.location.host;this.v="";this.K=a.optOutAllowed;
this.N=a.legacyTalkSignedIn;this.Ia=a.useSpareMole;this.F=a.conversationId};Pp.A||_.r(Pp,Jp);kq.ma=Pp;
var mq=function(a){var b={},c=_.Lb(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.y(a,2)&&27!=_.y(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.Lb(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.Lb(a,8,"0");b.propertyName=lq(_.y(a,2));b.locale=_.y(a,4);b.hideProfileCard=!0;b.parentToken=_.y(a,3);b.isRtl=Ep(a,6,!1);b.lazy=Ep(a,7,!1);b.entityId=_.y(a,9);b.hostSettings=_.y(a,5);b.jsmode=_.y(a,11);b.isFullFrame=Ep(a,13,!1);b.rosterId=_.Lb(a,12,"talk_roster");
b.rosterIframeId=_.Lb(a,12,"talk_roster");b.rosterIframeIdB=_.Lb(a,15,"gtn-roster-iframe-id-b");b.derp=!!Ep(a,16,!1);c=_.C(a,cq,14);null!=c&&(b.isCentralRoster=Ep(c,1,!1),b.useQuasarPanels=Ep(c,2,!1));c=_.C(a,$p,10);null!=c&&(b.moleManagerLeftMargin=_.y(c,1),b.moleManagerMiddleMargin=_.y(c,2),b.moleManagerRightMargin=_.y(c,3),b.moleManagerNoMoleAreaMargin=_.y(c,4),b.moleManagerBoundingElementId=_.y(c,5),b.moleWidth=_.y(c,6),b.moleHeight=_.y(c,7),b.minimizedMoleHeight=_.y(c,8));c=_.C(a,aq,18);null!=
c&&(b.optOutAllowed=Ep(c,1,!0),d=_.C(c,bq,3),null!=d&&(b.legacyTalkSignedIn=Ep(d,1,!0)),c=_.B(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new gq;_.z(c,2,!0);_.z(c,1,!0);_.z(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=Ep(a,17,!1);b.conversationId=_.y(a,19);return b},lq=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";
case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},nq=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Te(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var oq=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.g=new _.N(this);_.I(this,this.g);var f=_.Oa;d=new _.Q(a.g+a.o);Ep(a.c,2,!1)||(_.R(d,"ts","0"),_.R(d,"re",a.Nb),_.R(d,"ref",a.Fb));_.R(d,"client","sm");_.R(d,"prop",a.ab);_.R(d,"nav","true");_.R(d,"fid",a.a);a.j&&_.R(d,"debug",a.j);_.R(d,"os",_.nb);_.R(d,"stime",c);a.xa&&_.R(d,"hc",a.xa);for(c=0;c<Hp.length;++c);b=_.fd(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.fd(_.D(a.c)));a.m&&_.R(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.R(d,
"ua",f);a.wa&&_.R(d,"pvt",a.wa);a.bb&&_.R(d,"hsmc","true");_.n(a.V)&&_.R(d,"logl",a.V);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.Q(window.location.href);"false"==Bp(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.Hb)&&_.R(d,"jsmode",f);(f=Bp(b,"cssmode"))&&_.R(d,"cssmode",f);(f=Bp(b,"convid"))&&_.R(d,"convid",f);if(f=b.g.T("convp"))_.ma(f)||(f=[String(f)]),_.af(d.g,"convp",f);(f=Bp(b,"smexp"))&&_.R(d,"smexp",
f);f=b.g.T("mods");a.Ib&&f.push("lazy");e&&(f=_.Ea(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=Bp(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=Bp(b,"eid");_.Ia(_.Na(e))||_.R(d,"eid",e);_.Ia(_.Na(this.a.D))||_.R(d,"eid",this.a.D);null!=this.a.l&&_.R(d,"pos",this.a.l);_.n(a.Ga)&&_.R(d,"uiv",this.a.Ga);a.I&&_.R(d,"css",a.I);e=a.locale||Bp(b,"hl");null!=e&&_.R(d,"hl",e);_.n(a.Ja)&&_.R(d,"uj",a.Ja);null!=a.O&&_.R(d,"hpc",a.O);null!=a.U&&_.R(d,"hsm",
a.U);null!=a.S&&_.R(d,"hro",a.S);null!=a.M&&_.R(d,"hrc",a.M);null!=a.L&&_.R(d,"hotr",a.L);null!=a.ba&&_.R(d,"pop",a.ba);_.R(d,"pal","1");null!=a.Ha&&_.R(d,"uqp",a.Ha);null!=a.K&&_.R(d,"gooa",a.K);null!=a.N&&_.R(d,"gltsi",a.N);null!=a.Ia&&_.R(d,"gusm",a.Ia);null!=a.silent&&_.R(d,"sl",a.silent);a.fb&&_.R(d,"icr","1");a.Na&&_.R(d,"hpl","1");a.ga&&_.R(d,"hs",a.ga);a.B&&_.R(d,"dc",_.fd(_.D(a.B)));null!=a.va&&_.R(d,"molew",a.va);null!=a.ua&&_.R(d,"moleh",a.ua);null!=a.ta&&_.R(d,"mmoleh",a.ta);a.Qb&&_.R(d,
"derp","1");a.v&&_.R(d,"fcho",a.v);null!=a.Fa&&_.R(d,"two",a.Fa);null!=a.F&&_.R(d,"convid",a.F);_.R(d,"host","1");_.R(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.ha)()).toString(36));this.c=d.toString()};_.r(oq,_.F);oq.prototype.install=function(a,b){pq(this,a,b,_.ka)};
var pq=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Jb,a.b.body.appendChild(e));a=(0,_.q)(function(){var f="";this.a.gb||(f="height:400px");var g=_.cd(new _.bd(this.b),"IFRAME");_.$c(g,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:f,"aria-hidden":"true",allow:"microphone *; autoplay *"});_.Yc("talk_loading_msg",e)||_.ad(e);e.appendChild(g);var h=this.b.getElementById(this.a.a);_.ze(this.g,h,["load","error"],function(l){h.contentWindow.postMessage("AllowFrame: Chat", "*");d(l)});h.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var qq=function(a){var b=_.Ue(_.y(a,2),"/webchat/extension-start");_.y(a,5)&&_.R(b,"e",_.y(a,5));return new _.jc(function(c,d){_.ne(b,function(e){_.we(e.target)||d();try{var f=e.target;try{var g=f.a?f.a.responseText:""}catch(l){g=""}var h=JSON.parse(g);c(new _.Ee(h))}catch(l){d(l.message)}})})};
var sq=function(){var a=this;_.N.call(this);_.P("Starting ...");this.listen(window,"unload",this.$);this.b=new _.Ae(JSON.parse(decodeURI(location.hash.substr(1))));this.a=Fp(_.y(this.b,1));_.I(this,this.a);this.g=new _.pf;_.I(this,this.g);zp(qq(this.b).then(function(b){return rq(a,b)}),function(b){_.P("Failed to start : %s.",b||"")})},tq;_.r(sq,_.N);
var rq=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.y(b,1))){var c=new Zp,d=_.Te(_.y(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.z(c,1,e);_.z(c,2,23);_.z(c,13,!0);_.z(c,17,!0);dq(c,_.y(b,1));fq(c,_.y(a.b,4));eq(c,_.y(a.b,3)||"en");b=mq(c);var f=new kq(b,b.endpointConfig);f.g=nq(f.g,f.b);f.v=location.origin;f.a="gtn-roster-iframe-id-q";b=Ip(f.g,f.a);b=new oq(f,b,(0,_.ha)(),window.document);_.I(a,b);pq(b,f.Ob,function(){},function(){_.uf(a.g,document.getElementById(f.a).contentWindow,"31ACFC0_","google.com"); Cp(a.g,a.a);Cp(a.a,a.g);a.a.sendMessage(new Ap)})}};_.ta("default_host._DumpException",function(a){return console.error(a.stack)});_.Mf();if(!tq||tq.G)tq=new sq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
